### ISSUE TITLE
Open cover error - missing pdbs

### ISSUE THREAD

**Issue by ChrisGuildhall** [FortuneN/FineCodeCoverage#105]
### Installed product versions
- Visual Studio: 2019 community Version 4.8.04084
- This extension: 1.1.127

### Description
At start up, FCC gives an error says:

Fine Code Coverage : Initializing

Fine Code Coverage : Failed Initialization
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.ReadAllText(String path)
   at FineCodeCoverage.Engine.MsTestPlatform.MsTestPlatformUtil.GetMsTestPlatformVersion() in C:\projects\finecodecoverage\FineCodeCoverage\Core\MsTestPlatform\MsTestPlatformUtil.cs:line 72
   at FineCodeCoverage.Engine.MsTestPlatform.MsTestPlatformUtil.Initialize(String appDataFolder) in C:\projects\finecodecoverage\FineCodeCoverage\Core\MsTestPlatform\MsTestPlatformUtil.cs:line 38
   at FineCodeCoverage.Engine.FCCEngine.Initialize(IInitializeStatusProvider initializeStatusProvider) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 98
   at FineCodeCoverage.Impl.Initializer.Initialize() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscovery\Initializer.cs:line 39

### Steps to recreate
1. Install Extension
2. Wait till FCC initialization starts
3. The error pops up on the FCC window.

### Current behavior
It's not initializing and code coverage will fail.

### Expected behavior
It shouldn't say Fine Code Coverage : Failed Initialization.

**Comment by tonyhallett** [comment]
This is strange. It suggests that vstest.console.exe exists in a subdirectory of AppData/Local/FineCodeCoverage/msTestPlatform but the nuspec is missing from the unzipped downloaded nupkg.  Have you deleted the nuspec or have you tried a later version of FCC and returned to version 1.1.127 ?

A fix will be to close vs, delete the msTestPlatform folder ( AppData/Local/FineCodeCoverage/msTestPlatform ) and reopen vs.

**Comment by tonyhallett** [comment]
@FortuneN 
There is a bug at this line https://github.com/FortuneN/FineCodeCoverage/blob/67af3a6dddb53ae44e139006dc2f0ef9a0bc4f57/FineCodeCoverage/Core/MsTestPlatform/MsTestPlatformUtil.cs#L66 although it is strange that the nuspec is not present in ths case. I replaced installing at initialization with embedded tool zips with my last [merged pull](https://github.com/FortuneN/FineCodeCoverage/pull/103) so there is no need to change this line but the marketplace does need to be updated.

**Comment by FortuneN** [comment]
I was ready to publish but I noticed you had reopened the issue #40

**Comment by tonyhallett** [comment]
Yes it was closed by my comment in the pull. I wanted it open until it was on the marketplace. It is good for publish. 

I am finalizing a build task that generates the zips automatically. This will keep us up to date as the tools change. This will be done today

**Comment by ChrisGuildhall** [comment]
Yes I did install a later version of FCC and reinstalled the one from Vs market place.

**Comment by ChrisGuildhall** [comment]
Fine Code Coverage : Initializing

Fine Code Coverage : MsTestPlatform Get Info Not Installed

Fine Code Coverage : MsTestPlatform Install
Installed version 16.7.1

Fine Code Coverage : Failed Initialization
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.ReadAllText(String path)
   at FineCodeCoverage.Engine.OpenCover.OpenCoverUtil.GetOpenCoverVersion() in C:\projects\finecodecoverage\FineCodeCoverage\Core\OpenCover\OpenCoverUtil.cs:line 76
   at FineCodeCoverage.Engine.OpenCover.OpenCoverUtil.Initialize(String appDataFolder) in C:\projects\finecodecoverage\FineCodeCoverage\Core\OpenCover\OpenCoverUtil.cs:line 42
   at FineCodeCoverage.Engine.FCCEngine.Initialize(IInitializeStatusProvider initializeStatusProvider) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 99
   at FineCodeCoverage.Impl.Initializer.Initialize() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscovery\Initializer.cs:line 39

This is what I get after I removed MsTestPlatform folder

**Comment by tonyhallett** [comment]
You will need to do the same with the other folders then.

**Comment by tonyhallett** [comment]
The later version that you installed has been released to the marketplace. The issue should resolve by shutting down and reopening visual studio.

**Comment by tonyhallett** [comment]
@ChrisGuildhall Is it working for you now

**Comment by ChrisGuildhall** [comment]
@tonyhallett not yet I dont know if it's the way my project is setup. But when I run tests now it gives no result:
Test Run Successful.

Total tests: 2
     Passed: 2
 Total time: 2.8130 Seconds
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

**Comment by tonyhallett** [comment]
Is your project open source ?

**Comment by tonyhallett** [comment]
Do you get coverage when run directly with coverlet / open over ?

**Comment by ChrisGuildhall** [comment]
It's not open since it's under educational organization, but I can zip it and share it.
How do I run coverlet/open over directly ? @tonyhallett

**Comment by tonyhallett** [comment]
If you share it I will have a look

**Comment by tonyhallett** [comment]
Your error message is an OpenCover message.

https://github.com/OpenCover/opencover/wiki/Usage
https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf

You can find OpenCover installed in C:\Users\tonyh\AppData\Local\FineCodeCoverage\openCover\4.7.922\tools\OpenCover.Console.exe

The FCC Output Window shows the arguments that FCC uses with the console.

If you show me that output it would help determine the issue - in particular if you are excluding all of your projects from coverage.

**Comment by ChrisGuildhall** [comment]
@tonyhallett 
This is the output
Fine Code Coverage : Initializing

Fine Code Coverage : Initialized

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (UnitTest)

Fine Code Coverage : OpenCover Run (UnitTest) Arguments 
 -mergebyhash 
 -hideskipped:all 
 -register:path64 
 "-target:C:\Users\Chris Chen\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" 
 "-excludebyfile:**/Migrations/*" 
 "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" 
 "-targetargs:\"C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\build-output\UnitTest.dll\" " 
 "-output:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml"

Fine Code Coverage : OpenCover Run (UnitTest)
Executing: C:\Users\Chris Chen\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Passed DXTest [129 ms]
  Passed PSOTest [< 1 ms]

Test Run Successful.
Total tests: 2
     Passed: 2
 Total time: 2.6725 Seconds
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-03-17T13:24:46: Arguments
2021-03-17T13:24:46:  -targetdir:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output
2021-03-17T13:24:46:  -reports:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml
2021-03-17T13:24:46:  -reporttypes:Cobertura
2021-03-17T13:24:46: Writing report file 'C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-03-17T13:24:46: Report generation took 0.1 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:C:\USERS\CHRIS CHEN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_EB2F3BB1\EXTENSIONS\BN3WV4TX.EXN\ReportGeneratorPlugins.dll"
"-reporttypes:FccDark"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-03-17T13:24:47: Arguments
2021-03-17T13:24:47:  -targetdir:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output
2021-03-17T13:24:47:  -reports:C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-03-17T13:24:47:  -plugins:C:\USERS\CHRIS CHEN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_EB2F3BB1\EXTENSIONS\BN3WV4TX.EXN\ReportGeneratorPlugins.dll
2021-03-17T13:24:47:  -reporttypes:FccDark
2021-03-17T13:24:47: Writing report file 'C:\Users\Chris Chen\Documents\DFS2\src\DX12\x64\Debug\fine-code-coverage\coverage-tool-output\index.html'
2021-03-17T13:24:47: Report generation took 0.2 seconds

Fine Code Coverage : ================================== DONE ==================================

**Comment by tonyhallett** [comment]
@ChrisGuildhall Thanks for that.  Are you able to share the project ?

**Comment by tonyhallett** [comment]
closing due to inactivity
