### ISSUE TITLE
Failing to get coverage.cobertura.xml for project (zero coverage result)

### ISSUE THREAD

**Issue by andre-f-paggi** [FortuneN/FineCodeCoverage#106]
### Installed product versions
- Visual Studio: 2019 Professional Version 16.9.0
- This extension: 1.1.129

### Description
I get an error in a single test project everytime I try to test it, in which it cannot read the 'coverage.cobertura.xml'. The other two test projects run ok.

The error is:

```
Fine Code Coverage : Run Coverage Tool (MyProject.UnitTest)

Fine Code Coverage : Coverlet Collector Run (MyProject.UnitTest) Arguments 
"C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\MyProject.UnitTest.dll" --blame --nologo --diag "C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/diagnostics.log" --settings "C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/FCC.runsettings" --results-directory "C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"

Fine Code Coverage : Coverlet Collector Run (MyProject.UnitTest)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.10] MyProject.UnitTest: Skipping test case with duplicate ID '7c2764be4065cf2c08e1dc7e26f724b65edbd339' ('MyProject.UnitTest.Converters.FixedIncomeConvertTest.ShouldOnlyCaptureToAssetClass(description: "", expected: Alternatives)' and 'MyProject.UnitTest.Converters.FixedIncomeConvertTest.ShouldOnlyCaptureToAssetClass(description: "", expected: Alternatives)')

Attachments:
  C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\e05a9f03-bed6-4436-af8a-f57ba1302c06\coverage.cobertura.xml
Passed!  - Failed:     0, Passed:   276, Skipped:     0, Total:   276, Duration: 2 s - MyProject.UnitTest.dll (netcoreapp3.1)

Fine Code Coverage : Run Coverage Tool (MyProject.UnitTest) Failed
System.Exception: Data collector did not generate coverage.cobertura.xml
   at FineCodeCoverage.Engine.Coverlet.CoverletDataCollectorGeneratedCobertura.CorrectPath(String coverageOutputFolder, String coverageOutputFile) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\DataCollector\CoverletDataCollectorGeneratedCobertura.cs:line 27
   at FineCodeCoverage.Engine.Coverlet.CoverletDataCollectorUtil.<RunAsync>b__25_1() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\DataCollector\CoverletDataCollectorUtil.cs:line 209
   at FineCodeCoverage.Core.Utilities.ProcessResponseProcessor.Process(ExecuteResponse result, Func`2 exitCodeSuccessPredicate, Boolean throwError, String title, Action successCallback) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Utilities\ProcessResponseProcessor.cs:line 32
   at FineCodeCoverage.Engine.Coverlet.CoverletDataCollectorUtil.<RunAsync>d__25.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\DataCollector\CoverletDataCollectorUtil.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<StepAsync>d__62.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 343
```

This error makes me get 0% coverage for that project target.

I checked the file 'coverage.cobertura.xml' is being generated and is filled correctly. 

Could this be a timeout error or maybe a file access level error?

Thanks in advance!

**Comment by tonyhallett** [comment]
Thanks. Is your project open source ?
You could try a previous vsix but it will not use coverlet collector. If you do you will need to delete the fine code coverage folder in appdata.

**Comment by andre-f-paggi** [comment]
No, its enterprise unfortunatly.

I tried some other versions, but with no success. I didn`t deleted the appData folder though, I will try for that now.

In the diagnostics.log file it says:

'
Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\repos\MyProject\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\testhost.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\repos\MyProject\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\testhost.runtimeconfig.json' file and specify the appropriate framework.
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
'

**Comment by tonyhallett** [comment]
I will add some further logging tomorrow and we can determine if it is indeed due to the cobertura file not being found and if so where it was expected.

**Comment by andre-f-paggi** [comment]
Thanks for that @tonyhallett. If you need the entire diagnostics files I can send it to you too.

**Comment by tonyhallett** [comment]
A minimal working example would be best and if that is not possible details of the test projects and the projects they are testing.

**Comment by tonyhallett** [comment]
The cobertura file is searched for in the correct directory and as your output shows it is written to that directory

> Attachments:
  C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\e05a9f03-bed6-4436-af8a-f57ba1302c06\coverage.cobertura.xml

So it seems that the code is looking for it too soon.  I could poll for it to be written but it is better to understand why this is happening for your particular solution.  

These are the requirements for coverlet data collector - please confim that you meet these.

> Requirements
You need to be running .NET Core SDK v2.2.401 or newer
You need to reference version 16.5.0 and above of Microsoft.NET.Test.Sdk
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />

**Comment by tonyhallett** [comment]
This [link](https://github.com/dotnet/runtime/issues/3569) might help regarding

> Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.

**Comment by andre-f-paggi** [comment]
@tonyhallett Unfortunetly I cannot send a working example, only if I can craft a similar one without much code, but I don`t know if is going to work.

My project is using .net core 3.1 and Microsoft.NET,Sdk 16.9.1.

The link you send me, when I change the runsettings json, the hostpolicy error disappears, so I don't think this is still an error anymore. I think it is more likely to be something with accessing the file too early.

Have you already changed something in the logging?

**Comment by tonyhallett** [comment]
I haven't changed the logging as there is nothing to log. 
I will change to poll for the file.

**Comment by tonyhallett** [comment]
This [vsix](https://ci.appveyor.com/api/buildjobs/mjgxm3lnenj1mdnq/artifacts/FineCodeCoverage.vsix) implements polling - if the file is not output in 10 seconds then there is an exception.
Please let me know if this resolves the issue.

**Comment by andre-f-paggi** [comment]
Now it is stuck in that project and doesn't continue. Want the logs?

**Comment by tonyhallett** [comment]
No I will check the code for the error. Sorry coding in a hurry on a train. Will get back to you as soon as I get the chance.

**Comment by andre-f-paggi** [comment]
No problem, let me know if I can help you any other how.

**Comment by andre-f-paggi** [comment]
Tried the new extension, but it stills cannot find the .xml

```
Fine Code Coverage : Initializing

Fine Code Coverage : Initialized

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (MyProject.UnitTest)

Fine Code Coverage : Coverlet Collector Run (MyProject.UnitTest) Arguments 
"C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\MyProject.UnitTest.dll" --blame --nologo --diag "C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/diagnostics.log" --settings "C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/FCC.runsettings" --results-directory "C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"

Fine Code Coverage : Coverlet Collector Run (MyProject.UnitTest)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.40] MyProject.UnitTest: Skipping test case with duplicate ID '7c2764be4065cf2c08e1dc7e26f724b65edbd339' ('MyProject.UnitTest.Converters.FixedIncomeConvertTest.ShouldOnlyCaptureToAssetClass(description: "", expected: Alternatives)' and 'MyProject.UnitTest.Converters.FixedIncomeConvertTest.ShouldOnlyCaptureToAssetClass(description: "", expected: Alternatives)')

Attachments:
  C:\repos\MyProject\test\MyProject.UnitTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\c0d592ed-cd92-4f3a-abc3-0121032d7691\coverage.cobertura.xml
Passed!  - Failed:     0, Passed:   276, Skipped:     0, Total:   276, Duration: 3 s - MyProject.UnitTest.dll (netcoreapp3.1)

Fine Code Coverage : Run Coverage Tool (MyProject.UnitTest) Failed
System.Exception: Data collector did not generate coverage.cobertura.xml
   at FineCodeCoverage.Engine.Coverlet.CoverletDataCollectorGeneratedCobertura.<CorrectPathAsync>d__5.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\DataCollector\CoverletDataCollectorGeneratedCobertura.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Core.Utilities.ProcessResponseProcessor.<ProcessAsync>d__2.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Utilities\ProcessResponseProcessor.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Coverlet.CoverletDataCollectorUtil.<RunAsync>d__25.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\DataCollector\CoverletDataCollectorUtil.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<StepAsync>d__62.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 343

Fine Code Coverage : ================================== DONE ==================================
```

**Comment by andre-f-paggi** [comment]
Some additional logs from the `diagnostics.log` file:

```
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.600, 245401386981, vstest.console.dll, DataCollectionRequestSender.SendAfterTestRunStartAndGetResult : Received message: (DataCollection.AfterTestRunEndResult) -> {
  "AttachmentSets": [
    {
      "Uri": "datacollector://Microsoft/CoverletCodeCoverage/1.0",
      "DisplayName": "XPlat code coverage",
      "Attachments": [
        {
          "Description": "",
          "Uri": "file://C:/repos/MyProject.UnitTest/bin/Debug/netcoreapp3.1/fine-code-coverage/coverage-tool-output/7c272b01-94a5-4e73-875c-8e307da58e87/coverage.cobertura.xml"
        }
      ]
    }
  ],
  "Metrics": {}
}
TpTrace Information: 0 : 19336, 13, 2021/03/09, 16:42:43.605, 245401438195, vstest.console.dll, ProxyDataCollectionManager.InvokeDataCollectionServiceAction: Completed.
TpTrace Warning: 0 : 19336, 9, 2021/03/09, 16:42:43.639, 245401776902, vstest.console.dll, DataCollectionLauncher.ErrorReceivedCallback datacollector standard error line: 
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.647, 245401853125, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Information: 0 : 19336, 13, 2021/03/09, 16:42:43.647, 245401855967, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.647, 245401859543, vstest.console.dll, ParallelProxyExecutionManager: HandlePartialRunComplete: Total completed clients = 1, Run complete = True, Run canceled: False.
TpTrace Information: 0 : 19336, 7, 2021/03/09, 16:42:43.654, 245401928162, vstest.console.dll, DataCollectionLauncher.ExitCallBack: Data collector exited with exitcode: 0 error: ''
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.665, 245402039845, vstest.console.dll, TestRunRequest:TestRunComplete: Starting. IsAborted:False IsCanceled:False.
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.666, 245402043493, vstest.console.dll, TestLoggerManager.HandleTestRunComplete: Ignoring as the object is disposed.
TpTrace Information: 0 : 19336, 13, 2021/03/09, 16:42:43.666, 245402047702, vstest.console.dll, TestRunRequest:TestRunComplete: Completed.
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.666, 245402049728, vstest.console.dll, TestRequestSender.SetOperationComplete: Setting operation complete.
TpTrace Verbose: 0 : 19336, 1, 2021/03/09, 16:42:43.666, 245402048908, vstest.console.dll, TestRunRequest.Dispose: Starting.
TpTrace Information: 0 : 19336, 13, 2021/03/09, 16:42:43.667, 245402051525, vstest.console.dll, SocketServer.Stop: Stop server endPoint: 127.0.0.1:58837
TpTrace Information: 0 : 19336, 1, 2021/03/09, 16:42:43.667, 245402053577, vstest.console.dll, TestRunRequest.Dispose: Completed.
TpTrace Information: 0 : 19336, 13, 2021/03/09, 16:42:43.667, 245402055057, vstest.console.dll, SocketServer.Stop: Cancellation requested. Stopping message loop.
TpTrace Information: 0 : 19336, 1, 2021/03/09, 16:42:43.667, 245402056997, vstest.console.dll, TestRequestManager.RunTests: run tests completed.
TpTrace Information: 0 : 19336, 13, 2021/03/09, 16:42:43.667, 245402058702, vstest.console.dll, SocketServer.PrivateStop: Stop server endPoint: 127.0.0.1:58837 error: 
TpTrace Information: 0 : 19336, 1, 2021/03/09, 16:42:43.668, 245402060834, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is completed.
TpTrace Verbose: 0 : 19336, 1, 2021/03/09, 16:42:43.668, 245402065272, vstest.console.dll, Executor.Execute: Exiting with exit code of 0
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.668, 245402069135, vstest.console.dll, LengthPrefixCommunicationChannel.Dispose: Dispose reader and writer.
TpTrace Information: 0 : 19336, 13, 2021/03/09, 16:42:43.669, 245402071824, vstest.console.dll, SocketServer.Stop: Raise disconnected event endPoint: 127.0.0.1:58837 error: 
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.669, 245402074095, vstest.console.dll, TestRequestSender: OnTestRunAbort: Operation is already complete. Skip error message.
TpTrace Verbose: 0 : 19336, 13, 2021/03/09, 16:42:43.669, 245402075979, vstest.console.dll, TcpClientExtensions.MessageLoopAsync: exiting MessageLoopAsync remoteEndPoint: 127.0.0.1:58839 localEndPoint: 127.0.0.1:58837
```

**Comment by andre-f-paggi** [comment]
The other projects run well:
![image](https://user-images.githubusercontent.com/8538938/110529955-ebd2c380-812a-11eb-9ffc-e7013f0b2454.png)

**Comment by tonyhallett** [comment]
This [vsix](https://ci.appveyor.com/api/buildjobs/2l2j90suk8p7ivop/artifacts/FineCodeCoverage.vsix) logs the folder that is searched for the generated cobertura file.

Is it the same as C:/repos/MyProject.UnitTest/bin/Debug/netcoreapp3.1/fine-code-coverage/coverage-tool-output ?
Perhaps you can watch the folder to see if and when the guid directory is created that contains coverage.cobertura.xml.

**Comment by tonyhallett** [comment]
Is there anything unusual with this problematic project ? Perhaps you can post the generated FCC.runsettings in the coverage-tool-output directory

**Comment by andre-f-paggi** [comment]
Yes, it is the same folder.

I noticed now that if throws an error just before it generates the file.

I seems like the file write of `cobertura.coverage.xml` is waiting until it throws the error to be generated.

Check this gif:
![fine-coverage2](https://user-images.githubusercontent.com/8538938/110674161-ad98db00-81e2-11eb-9be8-09db8a3e27c4.gif)

**Comment by tonyhallett** [comment]
Thanks. Will try a slightly different approach tomorrow

**Comment by tonyhallett** [comment]
This [vsix](https://ci.appveyor.com/api/buildjobs/gtjjn8308rdped2w/artifacts/FineCodeCoverage.vsix) sleeps between searches of the generated cobertura file.

**Comment by andre-f-paggi** [comment]
Sorry for the delay, it did not work too

**Comment by tonyhallett** [comment]
Are the projects that do not fail also using the data collector ?
Is there something unusual / different with the one that fails ?
Can you show the contents of the generated run settings ?

**Comment by tonyhallett** [comment]
> forgot to copy the runsettings to the build-output folder, that somehow does not generate it automaticaly

Are you saying that FCC.runsettings is not generated for you ?

**Comment by andre-f-paggi** [comment]
I suspect the error is that the path is too long for that project, sorry for not thinking of that earlier. Is there a limitation for the extension to work? Right now the path to the .xml file is 261 chars long

**Comment by andre-f-paggi** [comment]
> > forgot to copy the runsettings to the build-output folder, that somehow does not generate it automaticaly
> 
> Are you saying that FCC.runsettings is not generated for you ?

Yes, I have to manually copy it, bug now I think is something relative to long paths

**Comment by andre-f-paggi** [comment]
Oh man, that's it. It was a long path related error 🤦‍♂️. I feel so dumb for this, sorry for taking your time @tonyhallett

**Comment by tonyhallett** [comment]
I still do not understand why you are copying FCC.runsettings.  They should be generated for each project either based on your run settings or not.

**Comment by andre-f-paggi** [comment]
I guess it was for the same reason as the cobertura.xml not being found, long paths. When I shorted the path, it generates now that file and actually shows the coverage for that project

**Comment by tonyhallett** [comment]
Aside from the run settings generation - when you resolve the long path error, do you need to poll for the cobertura or does the current marketplace vsix work sufficiently ?

**Comment by andre-f-paggi** [comment]
I will try the marketplace vsix now

**Comment by andre-f-paggi** [comment]
It work too @tonyhallett. I think you can close this issue now. 

...Sometimes I forget how stupid are filepaths are in Windows
