### ISSUE TITLE
Exception: The calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by the-dext** [FortuneN/FineCodeCoverage#15]
### Installed product versions
- Visual Studio: 2019 Professional version 16.7.7
- This extension: 1.0.104

### Description
Running all unit tests causes fine code coverage to throw an exception which is logged in the Output (build) window.

### Steps to recreate
(using the 'Debug | Any CPU' configuration)
Select test window.
Choose run all tests.

### Current behavior
The exception thrown is: Fine Code Coverage : Error processing unit test events
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at FineCodeCoverage.Output.OutputToolWindowControl.Clear() in C:\projects\finecodecoverage\FineCodeCoverage\Output\OutputToolWindowControl.xaml.cs:line 54
   at FineCodeCoverage.Impl.TestContainerDiscoverer.OperationState_StateChanged(Object sender, OperationStateChangedEventArgs e) in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscoverer.cs:line 136

### Expected behavior
Code coverage to be collected/displayed.

**Comment by FortuneN** [comment]
Is the issue resolved; Can i close?

**Comment by FortuneN** [comment]
Please post a review

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
