### ISSUE TITLE
Group Policy Blocking FCC

### ISSUE THREAD

**Issue by steve09014098** [FortuneN/FineCodeCoverage#151]
### Installed product versions
- Visual Studio: 2019 Professional version 16.9.4
- This extension: Fine Code Coverage Version 1.1.141 Downloaded from VS Marketplace

### Description

I appreciate you have no control over Group Policies etc, however I can find no information as to what permissions FCC needs for where on the Windows 10 system.

I have a folder which has been opened up for running visual studio projects and all code and tests run from there without problem, but I am assuming that FCC accesses a folder somewhere else on the system that needs access.

Getting the following error when running FCC after unit tests.

```
Fine Code Coverage : Initializing

Fine Code Coverage : Initialized

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (DecoderTests)

Fine Code Coverage : Coverlet Run (DecoderTests) Arguments 
"C:\WorkArea\Code\Decoder\Unit Tests\DecoderTests\bin\Debug\net5.0\fine-code-coverage\build-output\DecoderTests.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--include-test-assembly
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "C:\WorkArea\Code\Decoder\Unit Tests\DecoderTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\DecoderTests.coverage.xml"
--targetargs "test  ""C:\WorkArea\Code\Decoder\Unit Tests\DecoderTests\bin\Debug\net5.0\fine-code-coverage\build-output\DecoderTests.dll"" --nologo --blame  --results-directory ""C:\WorkArea\Code\Decoder\Unit Tests\DecoderTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"" --diag ""C:\WorkArea\Code\Decoder\Unit Tests\DecoderTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output/diagnostics.log""  "

Fine Code Coverage : Run Coverage Tool (DecoderTests) Failed
System.ComponentModel.Win32Exception (0x80004005): This program is blocked by group policy. For more information, contact your system administrator
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CliWrap.Internal.ProcessEx.Start()
   at CliWrap.Command.<ExecuteAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CliWrap.Internal.Extensions.AsyncExtensions.<Select>d__0`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Core.Utilities.ProcessUtil.<ExecuteAsync>d__4.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Utilities\ProcessUtil.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Coverlet.CoverletConsoleUtil.<RunAsync>d__8.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\Console\CoverletConsoleUtil.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<StepAsync>d__62.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 343

Fine Code Coverage : ================================== DONE ==================================
```

**Comment by tonyhallett** [comment]
We unzip the tools required in AppData/Local/FineCodeCoverage

**Comment by tonyhallett** [comment]
I will add to the readme at a later date.
