### ISSUE TITLE
Fine Code Coverage window is blank

### ISSUE THREAD

**Issue by MSIT12806** [FortuneN/FineCodeCoverage#168]
The installation of the extension has worked. All of tests run successfully. When I open the "Fine Code Coverage" window it is simply empty.

Fine Code Coverage : ================================== ERROR ==================================

Fine Code Coverage : System.Exception: 2021-07-25T19:55:58: Arguments
2021-07-25T19:55:58:  -targetdir:C:\Gits\PoliticalAchievement\PoliticalAchievementTests\bin\Debug\.netcoreapp,version=v3.1\fine-code-coverage\coverage-tool-output
2021-07-25T19:55:58:  -reports:C:\Gits\PoliticalAchievement\PoliticalAchievementTests\bin\Debug\.netcoreapp,version=v3.1\fine-code-coverage\coverage-tool-output\PoliticalAchievementTests.coverage.xml
2021-07-25T19:55:58:  -reporttypes:Cobertura
2021-07-25T19:55:58: The short switch '-targetdir:C:\Gits\PoliticalAchievement\PoliticalAchievementTests\bin\Debug\.netcoreapp,version=v3.1\fine-code-coverage\coverage-tool-output' is not defined in the switch mappings.
2021-07-25T19:55:58:    at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Palmmedia.ReportGenerator.Core.Generator.GetConfiguration() in /_/src/ReportGenerator.Core/Generator.cs:line 275
   at Palmmedia.ReportGenerator.Core.Generator.GenerateReport(IReportConfiguration reportConfiguration) in /_/src/ReportGenerator.Core/Generator.cs:line 44
   於 FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<>c__DisplayClass13_0.<<RunReportGeneratorAsync>g__run|1>d.MoveNext() 於 C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs: 行 119
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<RunReportGeneratorAsync>d__13.MoveNext() 於 C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs: 行 133
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 FineCodeCoverage.Engine.FCCEngine.<RunAndProcessReportAsync>d__47.MoveNext() 於 C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs: 行 199
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass51_0.<<ReloadCoverage>b__0>d.MoveNext() 於 C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs: 行 295

**Comment by tonyhallett** [comment]
Is due to your folder name Debug.netcoreapp,version=v3.1

None of my projects have had this naming - normally is Debug/netcoreapp3.1

How have you set this up ?

**Comment by MSIT12806** [comment]
Cool, problem has been solved.
I checked my test project and found it didn't set target framework. 
thanks.
