### ISSUE TITLE
Cant found extension in VS Professional 2019 version

### ISSUE THREAD

**Issue by prarthana94** [FortuneN/FineCodeCoverage#172]
### Installed product versions
- Visual Studio: [example 2019 Professional]
- This extension: [example 1.1.141]

### Description
I have installed the extension but i cant see that in my VS output tab or any tab please suggest how can i find it .I have installed it from my visual studio as well as from market place both ways it gets installed successfully but when i open it it doesnt show. Please help ASAP. 

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
<img width="721" alt="fineCodeCoverage" src="https://user-images.githubusercontent.com/88875598/129315820-558da9aa-b987-4ae9-9ae0-e543a5855945.PNG">

  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
I don't have a computer to hand but I think it is View / Other windows / fine code coverage for the report window.  The FCC output pane should be present and contains diagnostic information when you run tests from test explorer that result in coverage collection

**Comment by tonyhallett** [comment]
Did your work it out ?

**Comment by prarthana94** [comment]
Yes i can see the extension in the path you provided but it doesnt seem to work somehow , i tested my unit case after that i am seeing in progress in fine code coverage.  Can you help in this  as what i am doing wrong ?
<img width="896" alt="fineCodeCoverage2" src="https://user-images.githubusercontent.com/88875598/129731863-4890f2c4-ba14-4b0e-8122-dee5920ba29b.PNG">

**Comment by prarthana94** [comment]
i meant i cant see anything in fine code coverage extension.

**Comment by tonyhallett** [comment]
Please post what you see in the FCC Output pane.

**Comment by prarthana94** [comment]
<img width="913" alt="fcc output" src="https://user-images.githubusercontent.com/88875598/129763422-60413f3b-ee5b-420e-adf2-da4bda8b992a.PNG">
<img width="926" alt="FCC Coverage output" src="https://user-images.githubusercontent.com/88875598/129763604-6dce6efa-5a97-4a01-8a21-d1677ce2e8ca.PNG">

**Comment by tonyhallett** [comment]
That's not the FCC Output Pane.

![image](https://user-images.githubusercontent.com/11292998/129764518-7f36a629-a657-4173-9bf7-2d8e7bb17f41.png)

**Comment by prarthana94** [comment]
<img width="917" alt="FCC Output Pane" src="https://user-images.githubusercontent.com/88875598/129765922-5ca49cb9-4e8f-4a9b-b4fd-510f72c4c268.PNG">

**Comment by tonyhallett** [comment]
I need to see all of it.

Is the code you are testing in the test dll ?

**Comment by prarthana94** [comment]
sorry my bad here is the full output , i didn't understand your question i am testing it in my unit test project if that answer your question. 

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (MS.XRM.Plugin.UnitTest)

Fine Code Coverage : OpenCover Run (MS.XRM.Plugin.UnitTest) Arguments 
 -mergebyhash 
 -hideskipped:all 
 -register:path32 
 "-target:C:\Users\prarthana.a.verma\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" 
 "-excludebyfile:**/Migrations/*" 
 "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" 
 "-targetargs:\"C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\build-output\MS.XRM.UnitTest.dll\" " 
 "-output:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\MS.XRM.Plugin.UnitTest.coverage.xml"

Fine Code Coverage : OpenCover Run (MS.XRM.Plugin.UnitTest)
Executing: C:\Users\prarthana.a.verma\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
2.7359
A total of 1 test files matched the specified pattern.
  Passed TestMethod1 [27 ms]
  Passed CheckPriorityIsNotHighToLow [6 ms]
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..
  Passed TestMethodforCreateOperation [687 ms]
  Failed TestMethodforUpdateOperation [275 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<01-01-2021 00:00:00>. Actual:<04-03-2021 00:00:00>. 
  Stack Trace:
     at MS.XRM.Plugin.UnitTest.CommonTestScenarioUnitTest.TestMethodforUpdateOperation() in C:\MyCodes\MS.XRM\MS.XRM.UnitTest\CommonTestScenarioUnitTest.cs:line 104

  Failed testmethod1 [3 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<Unable to proceed there are open approval task>. Actual:<>. 
  Stack Trace:
     at MS.XRM.Plugin.UnitTest.PluginUnitTests.testmethod1() in C:\MyCodes\MS.XRM\MS.XRM.UnitTest\PreCaseResolutionUnitTest.cs:line 93

  Passed TestIfApprovalTaskExist [141 ms]
  Passed TestWhetherApprovalTaskDoesntExist [315 ms]
  Passed TestNoOfReassign [2 ms]
  Failed TestIfRecordGetsAssignToUserOrTeam [7 ms]
  Error Message:
   Test method MS.XRM.UnitTest.RestrictRecordAssignmentUnitTest+RetrictRecordAssignmentTestCase.TestIfRecordGetsAssignToUserOrTeam threw exception: 
System.InvalidOperationException: The Id property must not be empty
  Stack Trace:
      at FakeXrmEasy.XrmFakedContext.ValidateEntity(Entity e)
   at FakeXrmEasy.XrmFakedContext.AddEntity(Entity e)
   at FakeXrmEasy.XrmFakedContext.AddEntityWithDefaults(Entity e, Boolean clone, Boolean usePluginPipeline)
   at FakeXrmEasy.XrmFakedContext.Initialize(IEnumerable`1 entities)
   at MS.XRM.UnitTest.RestrictRecordAssignmentUnitTest.RetrictRecordAssignmentTestCase.TestIfRecordGetsAssignToUserOrTeam() in C:\MyCodes\MS.XRM\MS.XRM.UnitTest\RestrictRecordAssignmentUnitTest.cs:line 62

  Failed TestIfCloseTypeIsSetToUser [13 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<0>. Actual:<(null)>. 
  Stack Trace:
     at MS.XRM.UnitTest.SetTaskCloseTypeAsUserUnitTest.SetTaskCloseTypeUnitTest.TestIfCloseTypeIsSetToUser() in C:\MyCodes\MS.XRM\MS.XRM.UnitTest\SetTaskCloseTypeAsUserUnitTest.cs:line 62


Total tests: 10
     Passed: 6
     Failed: 4
 Total time: 3.6709 Seconds
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

Test Run Failed.

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\MS.XRM.Plugin.UnitTest.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-08-17T22:13:30: Arguments
2021-08-17T22:13:30:  -targetdir:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output
2021-08-17T22:13:30:  -reports:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\MS.XRM.Plugin.UnitTest.coverage.xml
2021-08-17T22:13:30:  -reporttypes:Cobertura
2021-08-17T22:13:31: Writing report file 'C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-08-17T22:13:31: Report generation took 0.1 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:c:\users\prarthana.a.verma\appdata\local\microsoft\visualstudio\16.0_f7e84e1a\extensions\dqgigsdb.2es\ReportGeneratorPlugins.dll"
"-reporttypes:FccLight"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-08-17T22:13:31: Arguments
2021-08-17T22:13:31:  -targetdir:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output
2021-08-17T22:13:31:  -reports:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-08-17T22:13:31:  -plugins:c:\users\prarthana.a.verma\appdata\local\microsoft\visualstudio\16.0_f7e84e1a\extensions\dqgigsdb.2es\ReportGeneratorPlugins.dll
2021-08-17T22:13:31:  -reporttypes:FccLight
2021-08-17T22:13:32: Writing report file 'C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\index.html'
2021-08-17T22:13:32: Report generation took 0.4 seconds

Fine Code Coverage : ================================== DONE ==================================

**Comment by tonyhallett** [comment]
There has yet to be an issue created with the output you have provided

> Data collector 'UnitTestIsolation' message: No Microsoft .NET applications were launched during the test run. Launch applications from Explorer or a new command prompt after a test case has started. If no .NET application is being tested, disable the Test Impact and IntelliTrace diagnostic data adapters..

This is a coverlet message

> No results, this could be for a number of reasons. The most common reasons are:

1) missing PDBs for the assemblies that match the filter please review the
output file and refer to the Usage guide (Usage.rtf) about filters.
2) the profiler may not be registered correctly, please refer to the Usage
guide and the -register switch.

I did a quick search in [coverlet's issues ](https://github.com/coverlet-coverage/coverlet/issues) but there was no results.

Can you describe your solution or give me access ?

FCC copies the output to a new folder and runs tests from that - could that be causing an issue ?
e.g bind/Debug/fine-code-coverage/build-output

**Comment by prarthana94** [comment]
I can't give you access but I can tell you the scenarios basically there are multiple test cases in one unit test project when I am trying to run one it works fine and run  successfully, not sure why this error is coming.

**Comment by tonyhallett** [comment]
What technology area is this ?
Are you using Microsoft Fakes ?

**Comment by prarthana94** [comment]
No fakexrmeasy

**Comment by tonyhallett** [comment]
So in the context of fakexrmeasy does FCC's behaviour of moving the dlls to a new location likely to be the cause of the issue ?

I was incorrect earlier by mentioning Coverlet.  It is OpenCover that it providing coverage

You could run OpenCover manually and see if you get results.  

Please review the [wiki pages](https://github.com/opencover/opencover/wiki/_pages) on how to use OpenCover and take particular interest in the [Usage guide](https://github.com/opencover/opencover/wiki/Usage).

It is installed here - C:\Users\***\AppData\Local\FineCodeCoverage\openCover

There is a chance that fakexrmeasy is the issue.
If you see this issue https://github.com/OpenCover/opencover/issues/883 which is related to Fakes and not fakexrmeasy.  

> Both Fakes and OpenCover use the profiling API and as you can imagine things don't always play well.

**Comment by prarthana94** [comment]
Okay will try and update

**Comment by tonyhallett** [comment]
I personally would run OpenCover manually to see if FCC is the issue.

**Comment by tonyhallett** [comment]
@prarthana94 Did you get to the root of the problem ?

**Comment by prarthana94** [comment]
@tonyhallett  sorry for the late reply but i think the root cause is below error that i am getting in FCC output and i couldnt understand how to run OpenCover manually can you help with any video . 

Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

**Comment by tonyhallett** [comment]
Yes that is the cause of the error.

These are the arguments for OpenCover
```
-mergebyhash
-hideskipped:all
-register:path32
"-target:C:\Users\prarthana.a.verma\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
"-excludebyfile:**/Migrations/"
"-excludebyattribute:(.ExcludeFromCodeCoverage)|(.ExcludeFromCodeCoverageAttribute)|(.ExcludeFromCoverage)|(.ExcludeFromCoverageAttribute)|(.GeneratedCode)|(*.GeneratedCodeAttribute)"
"-targetargs:"C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\build-output\MS.XRM.UnitTest.dll" "
"-output:C:\MyCodes\MS.XRM\MS.XRM.UnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\MS.XRM.Plugin.UnitTest.coverage.xml"
```

So cd to C:\Users\prarthana.a.verma\AppData\Local\FineCodeCoverage\openCover\4.7.922\
and OpenCover.Console **args from above ( replace new lines with a space)**

**Comment by tonyhallett** [comment]
See https://github.com/FortuneN/FineCodeCoverage/issues/191#issuecomment-965241097 for how another user ran OpenCover directly.
