### ISSUE TITLE
Error processing unit test events System.Runtime.InteropServices.COMException (0x80020006)

### ISSUE THREAD

**Issue by WeihanLi** [FortuneN/FineCodeCoverage#229]
### Installed product versions
- Visual Studio: [2022 Enterprise]
- This extension: [1.1.56]

### Description

Sometimes it could not generate the test coverage on the line

Error logs from the output:

```

Fine Code Coverage : Initializing

Fine Code Coverage : Initialized

Fine Code Coverage : Coverage collected when tests finish. RunInParallel option true for immediate

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : File synchronization duration : 00:00:00.1979920

Fine Code Coverage : Run Coverage Tool (iHerb.CMS.API.Portal.UnitTests)

Fine Code Coverage : Coverlet Run (iHerb.CMS.API.Portal.UnitTests) Arguments 
"C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\iHerb.CMS.API.Portal.UnitTests.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-file "**/*Test/*"
--exclude-by-file "**/*Test.cs"
--exclude-by-file "**/*UT.cs"
--exclude-by-attribute "GeneratedCode"
--exclude-by-attribute "ExcludeFromCodeCoverage"
--include-test-assembly
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\iHerb.CMS.API.Portal.UnitTests.coverage.xml"
--targetargs "test  ""C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\iHerb.CMS.API.Portal.UnitTests.dll"" --nologo --blame  --results-directory ""C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"" --diag ""C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (iHerb.CMS.API.Portal.UnitTests)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.
Passed!  - Failed:     0, Passed:  1521, Skipped:     0, Total:  1521, Duration: 13 s - iHerb.CMS.API.Portal.UnitTests.dll (netcoreapp3.1)

Calculating coverage result...
  Generating report 'C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\iHerb.CMS.API.Portal.UnitTests.coverage.xml'
+-------------------------------------------+--------+--------+--------+
| Module                                    | Line   | Branch | Method |
+-------------------------------------------+--------+--------+--------+
| iHerb.CMS.API.Portal.Application          | 54.21% | 0%     | 54.21% |
+-------------------------------------------+--------+--------+--------+
| iHerb.CMS.API.Portal.Application.Services | 68.89% | 61.57% | 72.34% |
+-------------------------------------------+--------+--------+--------+
| iHerb.CMS.API.Portal.Domain               | 70.19% | 38%    | 73.59% |
+-------------------------------------------+--------+--------+--------+
| iHerb.CMS.API.Portal.Domain.Repositories  | 75.54% | 66.41% | 60.3%  |
+-------------------------------------------+--------+--------+--------+
| iHerb.CMS.API.Portal.Infrastructure       | 49.3%  | 39.49% | 71.42% |
+-------------------------------------------+--------+--------+--------+
| iHerb.CMS.API.Portal.ScheduleService      | 62.92% | 56.66% | 65.62% |
+-------------------------------------------+--------+--------+--------+
| iHerb.CMS.API.Portal.WebApi               | 87.71% | 81.06% | 90.42% |
+-------------------------------------------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 71.47% | 62.12% | 73.68% |
+---------+--------+--------+--------+
| Average | 66.96% | 49.02% | 69.7%  |
+---------+--------+--------+--------+

Fine Code Coverage : Completed coverage for iHerb.CMS.API.Portal.UnitTests : 00:00:24.3194083

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"
"-reports:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\iHerb.CMS.API.Portal.UnitTests.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2022-02-15T17:02:19: Arguments
2022-02-15T17:02:19:  -targetdir:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output
2022-02-15T17:02:19:  -reports:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\iHerb.CMS.API.Portal.UnitTests.coverage.xml
2022-02-15T17:02:19:  -reporttypes:Cobertura
2022-02-15T17:02:20: Writing report file 'C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2022-02-15T17:02:21: Report generation took 1.6 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"
"-reports:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:c:\users\weihan.li\appdata\local\microsoft\visualstudio\17.0_3ec80408\extensions\ogve5yl3.4cx\ReportGeneratorPlugins.dll"
"-reporttypes:FccLight"
"riskHotspotsAnalysisThresholds:metricThresholdForCyclomaticComplexity=30"
"riskHotspotsAnalysisThresholds:metricThresholdForCrapScore=15"
"riskHotspotsAnalysisThresholds:metricThresholdForNPathComplexity=200"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2022-02-15T17:02:21: Arguments
2022-02-15T17:02:21:  -targetdir:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output
2022-02-15T17:02:21:  -reports:C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml
2022-02-15T17:02:21:  -plugins:c:\users\weihan.li\appdata\local\microsoft\visualstudio\17.0_3ec80408\extensions\ogve5yl3.4cx\ReportGeneratorPlugins.dll
2022-02-15T17:02:21:  -reporttypes:FccLight
2022-02-15T17:02:21:  riskHotspotsAnalysisThresholds:metricThresholdForCyclomaticComplexity=30
2022-02-15T17:02:21:  riskHotspotsAnalysisThresholds:metricThresholdForCrapScore=15
2022-02-15T17:02:21:  riskHotspotsAnalysisThresholds:metricThresholdForNPathComplexity=200
2022-02-15T17:02:23: Writing report file 'C:\projects\test\cms.api.portal\iHerb.CMS.API.Portal.UnitTests\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\index.html'
2022-02-15T17:02:23: Report generation took 1.4 seconds

Fine Code Coverage : Processing cobertura

Fine Code Coverage : Processing report

Fine Code Coverage : ================================== DONE ==================================

Fine Code Coverage : Error processing unit test events
System.Runtime.InteropServices.COMException (0x80020006): Unknown name. (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))
   at System.Windows.Controls.WebBrowser.InvokeScript(String scriptName, Object[] args)
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<LogCoverageProcessAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<CombinedLogAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<TestExecutionStartingAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<OperationState_StateChanged>d__17.MoveNext()

Fine Code Coverage : ================================== ERROR ==================================

Fine Code Coverage : System.Runtime.InteropServices.COMException (0x80020006): Unknown name. (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))
   at System.Windows.Controls.WebBrowser.InvokeScript(String scriptName, Object[] args)
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<LogCoverageProcessAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass56_0.<<ReloadCoverage>b__0>d.MoveNext()

Fine Code Coverage : Error processing unit test events
System.Runtime.InteropServices.COMException (0x80020006): Unknown name. (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))
   at System.Windows.Controls.WebBrowser.InvokeScript(String scriptName, Object[] args)
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<LogCoverageProcessAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<CombinedLogAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<TestExecutionStartingAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<OperationState_StateChanged>d__17.MoveNext()

Fine Code Coverage : ================================== ERROR ==================================

Fine Code Coverage : System.Runtime.InteropServices.COMException (0x80020006): Unknown name. (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))
   at System.Windows.Controls.WebBrowser.InvokeScript(String scriptName, Object[] args)
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<LogCoverageProcessAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass56_0.<<ReloadCoverage>b__0>d.MoveNext()

Fine Code Coverage : Error processing unit test events
System.Runtime.InteropServices.COMException (0x80020006): Unknown name. (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))
   at System.Windows.Controls.WebBrowser.InvokeScript(String scriptName, Object[] args)
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<LogCoverageProcessAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<CombinedLogAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<TestExecutionStartingAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<OperationState_StateChanged>d__17.MoveNext()

Fine Code Coverage : ================================== ERROR ==================================

Fine Code Coverage : System.Runtime.InteropServices.COMException (0x80020006): Unknown name. (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))
   at System.Windows.Controls.WebBrowser.InvokeScript(String scriptName, Object[] args)
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<LogCoverageProcessAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass56_0.<<ReloadCoverage>b__0>d.MoveNext()

```

Test SDK package version:

``` xml
<PackageReference Include="coverlet.msbuild" Version="2.9.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
<PackageReference Include="Moq" Version="4.15.2" />
<PackageReference Include="xunit" Version="2.4.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

**Comment by tonyhallett** [comment]
> Sometimes it could not generate the test coverage on the line

Any pattern to this ? I feared this would occur. It happened as I was developing but I thought that I had tested it in the UI. The name does exist in the script it is a timing issue. You can install a previous version from releases. I will resolve in a couple of hours.

**Comment by tonyhallett** [comment]
@WeihanLi In 15 minutes there will be an update available.

**Comment by WeihanLi** [comment]
Hi @tonyhallett , sorry for the late reply, and great thanks for your soon fix, the FCC is really great, thanks for your work.

> Any pattern to this? 

Sorry that I did not notice that there's any pattern.

**Comment by tonyhallett** [comment]
No problem.
