### ISSUE TITLE
Cannot access DLL file / ArgumentNullException

### ISSUE THREAD

**Issue by pablocar80** [FortuneN/FineCodeCoverage#28]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 1.1.11

### Description
Crash calculating code coverage

### Steps to recreate
I run all my tests on a private repository (can't provide code)

### Current behavior
No results generated, got the following output with an error:

```txt
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Ensure Work Folder Exists (Testing)

Fine Code Coverage : Synchronize Output Files To Work Folder (Testing)

Fine Code Coverage : Synchronize Output Files To Work Folder (Testing) Failed
System.IO.IOException: The process cannot access the file 'C:\Gits\studio\Testing\bin\x64\fine-code-coverage\Testing.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at FineCodeCoverage.Engine.FileSynchronization.FileSynchronizationUtil.Synchronize(String sourceFolder, String destinationFolder) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FileSynchronization\FileSynchronizationUtil.cs:line 21
   at FineCodeCoverage.Engine.FCCEngine.<>c.<ReloadCoverage>b__25_7(CoverageProject project) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 422
   at FineCodeCoverage.Engine.Model.CoverageProject.Step(String stepName, Action`1 action) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 38

Fine Code Coverage : Error
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.ReadAllText(String path)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<>c__DisplayClass21_0.<OperationState_StateChanged>b__0() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscoverer.cs:line 163

Fine Code Coverage : ================================== ERROR ==================================
```

Sent beer on PayPal

**Comment by FortuneN** [comment]
Thanks for the beer.
Try this and let me know if the issue goes away.
[Fine Code Coverage v1.1.15.zip](https://github.com/FortuneN/FineCodeCoverage/files/5553190/Fine.Code.Coverage.v1.1.15.zip)
(It's a private build so i need feedback)

**Comment by pablocar80** [comment]
Hello Fortune, I wasn't able to reproduce the issue again -- even without installing the new build

**Comment by FortuneN** [comment]
It is reproducible.

This issue occurs when a new process is started before the old one completes
1) Run unit tests
2) As soon as the buttons the rerun test are active, run again
If you repeat (2) few times you will encounter the issue
 
Shouldn't be an issue anymore after version 1.1.15
