### ISSUE TITLE
Issue generating Code Coverage report

### ISSUE THREAD

**Issue by Not-That-Guy** [FortuneN/FineCodeCoverage#36]
### Installed product versions
- Visual Studio: 2019
- This extension: 1.1.25

### Description
Added coverlet.collector to test project and added Find Code Coverage VSIX to visual studio, is running fine in console but generating the report is not working.

### Current behavior
Not generating the report, throwing exception in the output window in visual studio:

_'""' is not recognized as an internal or external command, operable program or batch file._

```
Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:D:\dev\HP.Enterprise.Client\HP.Enterprise.Client.Test\bin\Debug\fine-code-coverage\_outputfolder"
"-reports:D:\dev\HP.Enterprise.Client\HP.Enterprise.Client.Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : Error
System.Exception: D:\dev\HP.Enterprise.Client\HP.Enterprise.Client.Test\bin\Debug\fine-code-coverage\_outputfolder>"" "-targetdir:D:\dev\HP.Enterprise.Client\HP.Enterprise.Client.Test\bin\Debug\fine-code-coverage\_outputfolder" "-reports:D:\dev\HP.Enterprise.Client\HP.Enterprise.Client.Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml" "-reporttypes:Cobertura"  1>"D:\dev\HP.Enterprise.Client\HP.Enterprise.Client.Test\bin\Debug\fine-code-coverage\_outputfolder\54a9a83e.bat.output" 

'""' is not recognized as an internal or external command, operable program or batch file.
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<RunReportGenerator>g__run|22_1(String outputReportType, String inputReports, <>c__DisplayClass22_0& ) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 215
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.RunReportGenerator(IEnumerable`1 coverOutputFiles, Boolean darkMode, String& unifiedHtmlFile, String& unifiedXmlFile, Boolean throwError) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 226
   at FineCodeCoverage.Engine.FCCEngine.ReloadCoverage(IEnumerable`1 projects, Boolean darkMode) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 486
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<>c__DisplayClass21_0.<OperationState_StateChanged>b__0() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscoverer.cs:line 164
```

### Expected behavior
Should generate the report and display in the Fine Code Coverage tab.

**Comment by FortuneN** [comment]
Hello @Not-That-Guy; I believe this is the same issue as Issue 32 (Can't get it work).

**Are you willing to do a skype/google meet/zoom/... meeting?**
We could install extension development tools in your VS, run the extension under the debugger step by step and see what's going on under the hood.

**Comment by t-johnson** [comment]
This looks like it may be resolved along with #62

**Comment by FortuneN** [comment]
@t-johnson thank you
@Not-That-Guy Please try latest update

**Comment by DamianDevOne** [comment]
@FortuneN sam issue. I have the newest version of VS2019 and FineCodeCoverage.

**Comment by tonyhallett** [comment]
Fixed by https://github.com/FortuneN/FineCodeCoverage/commit/75389cfffe94a985c71f5f176c326174897470b9
