### ISSUE TITLE
FCC not working on Visual Studio version 17.9.0 Preview 2.0

### ISSUE THREAD

**Issue by EnisBiberovic** [FortuneN/FineCodeCoverage#364]
### Installed product versions
- Visual Studio: Version 17.9.0 Preview 2.0 Professional
- This extension: 1.1.197

### Description
FCC fails on processing unit tests events

### Steps to recreate
1. Run tests
2. inspect the Output FCC

### Current behavior

Fine Code Coverage 19. 12. 2023. 20:11:50: Initializing
Fine Code Coverage 19. 12. 2023. 20:11:52: Initialized
Fine Code Coverage 19. 12. 2023. 20:14:15: Error processing unit test events
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> ReflectObject.PropertyDoesNotExistException: Property IsAborted with binding flags Instance, Public, NonPublic does not exist on Microsoft.VisualStudio.TestWindow.Messages.TestRunResponse
   at ReflectObject.PropertySetterBase`1.EnsureMemberExists()
   at ReflectObject.PropertySetterBase`1.Set(ReflectObjectProperties wrapper, Object reflectedObject)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ReflectObject.PropertySetter.GetPropertyValue(ReflectObjectProperties wrapper, Object reflectedObject)
   at ReflectObject.PropertySetterBase`1.Set(ReflectObjectProperties wrapper, Object reflectedObject)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FineCodeCoverage.Impl.TestOperationFactory.Create(IOperation operation)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<TestExecutionStartingAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<OperationState_StateChangedAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<TryAndLogExceptionAsync>d__37.MoveNext()
Fine Code Coverage 19. 12. 2023. 20:15:37: Error processing unit test events
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> ReflectObject.PropertyDoesNotExistException: Property IsAborted with binding flags Instance, Public, NonPublic does not exist on Microsoft.VisualStudio.TestWindow.Messages.TestRunResponse
   at ReflectObject.PropertySetterBase`1.EnsureMemberExists()
   at ReflectObject.PropertySetterBase`1.Set(ReflectObjectProperties wrapper, Object reflectedObject)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ReflectObject.PropertySetter.GetPropertyValue(ReflectObjectProperties wrapper, Object reflectedObject)
   at ReflectObject.PropertySetterBase`1.Set(ReflectObjectProperties wrapper, Object reflectedObject)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FineCodeCoverage.Impl.TestOperationFactory.Create(IOperation operation)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.ShouldConditionallyCollectWhenTestExecutionFinished(IOperation operation)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<TestExecutionFinishedAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<OperationState_StateChangedAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<TryAndLogExceptionAsync>d__37.MoveNext()

### Expected behavior
Expect that coverage data is collected and analyzed.

**Comment by tonyhallett** [comment]
FCC reflects on test explorer objects.  If they change object structure or visibility this will occur. Please use easier visual studio version. When 17.9 is released I will delve around.

**Comment by tonyhallett** [comment]
Fixed - updated in marketplace
