### ISSUE TITLE
Nothing happens after test run with xUnit

### ISSUE THREAD

**Issue by ElenaMorane** [FortuneN/FineCodeCoverage#38]
### Installed product versions
- Visual Studio: 2019 Professional
- xUnit: 2.4.1
- Xamarin Forms: 4.8

### Description
After running a test successfully no line with 
_Fine Code Coverage =============START==========
appears in the output window and also the Fine Code Coverage windows stays empty.
Did i not installed and/or initialized somthing? Or does the extension not work with Xamarin and/or xUnit?

**Comment by FortuneN** [comment]
Please attach a repro

**Comment by ElenaMorane** [comment]
Hmmm .... strange ... after a few days it works now ... don't know why .... really cool ... thanks a lot ... you earned the support :-)

**Comment by ElenaMorane** [comment]
Is there any possibility to support you, withourt paying so much fee's like in paypal?

**Comment by FortuneN** [comment]
I have these options (but they all go through PayPal. I'm open to ideas)
- https://liberapay.com/FortuneN
- https://ko-fi.com/FortuneN
- https://paypal.me/FortuneNgwenya
- https://www.buymeacoffee.com/FortuneN

I think i know why, it seems to not work at first and i will be handling it soon.
->The contents of the folder 'C:\Users\<USERNAME>\AppData\Local\FineCodeCoverage' are downloaded separately and because i don't yet display that progress on the UI, it creates this scenario where you may start using the tools before the download completes in the background. When it finally completes then 'it works now'

**Comment by bilalpandor** [comment]
Im seeing the same issue (it seems to be the same issue, which is why I havent opened another issue ticket).
Downloaded the extension yesterday. The tab is visible in VS but it's completely empty. Running my test suites has no effect.

I have also checked the folder mentioned above (C:\Users<USERNAME>\AppData\Local\FineCodeCoverage) and it does seem to have downloaded some of the files required (although I don't know if the download is complete).

Any help with this would be great. Thanks

**Comment by FortuneN** [comment]
@bilalpandor Is there a log in the build output window?

**Comment by scrow-gss** [comment]
I am getting the same error.  Here is the text in the output window: 

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Error processing unit test events
System.NullReferenceException: Object reference not set to an instance of an object.
   at FineCodeCoverage.Impl.RunSettingsRetriever.GetAndUpdateSolutionRunSettingsFilePath() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\RunSettingsRetriever.cs:line 27
   at FineCodeCoverage.Impl.RunSettingsRetriever.GetDefaultRunSettingsFilePath() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\RunSettingsRetriever.cs:line 42
   at FineCodeCoverage.Impl.RunSettingsRetriever.<GetRunSettingsFileAsync>d__1.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\RunSettingsRetriever.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at FineCodeCoverage.Impl.TestContainerDiscoverer.OperationState_StateChanged(Object sender, OperationStateChangedEventArgs e) in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscoverer.cs:line 171

**Comment by tonyhallett** [comment]
@scrow-gss 
Did your problem get resolved ?

**Comment by nytokyr** [comment]
Had the same issue on Vs 2019 Community. 
Anyway, after rebooting PC, it works !!!
