### ISSUE TITLE
Could not install the latest update

### ISSUE THREAD

**Issue by sbenzenko** [FortuneN/FineCodeCoverage#444]
### Installed product versions
- Microsoft Visual Studio Professional 2019
Version 16.11.38
- This extension: 1.1.222

### Description
Could not update or install the extension after the latest update. 

Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.CoreEditor (Microsoft.VisualStudio.Component.CoreEditor)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extensionToInstall, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

### Details in the log
The extension with ID 'fcc-f339fe606-9d51-4fca-895c-d50375137b62' is not installed to Visual Studio Professional 2019.
Extension Details...
	Identifier         : fcc-f339fe606-9d51-4fca-895c-d50375137b62
	Name               : Fine Code Coverage
	Author             : Fortune Ngwenya
	Version            : 1.1.222
	Description        : Visualize unit test code coverage easily for free in Visual Studio Community Edition (and other editions too)
	Locale             : en-US
	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage
	InstalledByMSI     : False
	SupportedFrameworkVersionRange : [4.7,)
	SignatureState     : Unsigned
	Supported Products : 
		Microsoft.VisualStudio.Community
			Version : [16.11,17.0)
			ProductArchitecture : x86
	References         : 
		-------------------------------------------------------
		Identifier   : Microsoft.VisualStudio.MPF.16.0
		Name         : Visual Studio MPF 16.0
		Version      : [16.0,17.0)
		MoreInfoURL  : 
		Nested       : No
	Prerequisites      : 
		-------------------------------------------------------
		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
		Name         : Visual Studio core editor
		Version      : [16.11,17.0)
Signature Details...
	Extension is not signed.
Extension cannot be installed to the following products due to missing prerequisites:
	Visual Studio Professional 2019
		-------------------------------------------------------
		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
		Name         : 
		Version      : [16.11,17.0)
		Error        : The prerequisite version specified does not match the version installed
Blocking processes:
InstallProgressPage ChangeType: 'SingleTarget' operationCount: '2' Text: 'Modifying Visual Studio Professional 2019...'
The following target products have been selected...
	Visual Studio Professional 2019

**Comment by tonyhallett** [comment]
This is odd given that the 2022 vsixmanifest is set up similarly

2019
```
<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[16.11, 17.0)" />
<Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[16.11,17.0)" DisplayName="Visual Studio core editor" />
```

2022
```
<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.10,18.0)">
<Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[17.10,18.0)" DisplayName="Visual Studio core editor" />
```

Will look into.

**Comment by tonyhallett** [comment]
Fix will be available in the marketplace in about 10 minutes.
