### ISSUE TITLE
FCC not working, everything is 0

### ISSUE THREAD

**Issue by Abhijith-Pradeep** [FortuneN/FineCodeCoverage#452]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.223

FCC is not working and the coverage tab is just plain. 
I had raised the issue earlier but sorry i couldn't respond promptly. I'm working on a .NET8 project and using xUnit as the testing framework. 
This is the output terminal:
"Fine Code Coverage 28-08-2024 7.40.01 PM: Initializing
Fine Code Coverage 28-08-2024 7.40.01 PM: Failed Initialization
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at FineCodeCoverage.Engine.OpenCover.OpenCoverUtil.Initialize(String appDataFolder, CancellationToken cancellationToken)
   at FineCodeCoverage.Engine.CoverageUtilManager.Initialize(String appDataFolder, CancellationToken cancellationToken)
   at FineCodeCoverage.Engine.FCCEngine.Initialize(CancellationToken cancellationToken)
   at FineCodeCoverage.Core.Initialization.Initializer.<InitializeAsync>d__13.MoveNext()
Fine Code Coverage 28-08-2024 7.42.37 PM: Skipping TestExecutionStarting as FCC not initialized
Fine Code Coverage 28-08-2024 7.43.09 PM: Skipping TestExecutionCancelAndFinished as FCC not initialized
Fine Code Coverage 29-08-2024 11.11.16 AM: Skipping TestExecutionStarting as FCC not initialized
Fine Code Coverage 29-08-2024 11.11.29 AM: Skipping TestExecutionFinished as FCC not initialized
Fine Code Coverage 29-08-2024 11.12.46 AM: Skipping TestExecutionStarting as FCC not initialized
Fine Code Coverage 29-08-2024 11.15.50 AM: Skipping TestExecutionCancelAndFinished as FCC not initialized
Fine Code Coverage 29-08-2024 11.37.58 AM: Skipping TestExecutionStarting as FCC not initialized
Fine Code Coverage 29-08-2024 11.38.03 AM: Skipping TestExecutionFinished as FCC not initialized"

![Screenshot 2024-08-29 114545](https://github.com/user-attachments/assets/3c255c74-dae3-4d53-ac3c-35d400869f15)

**Comment by tonyhallett** [comment]
FCC creates the C:\Users\***\AppData\Local\FineCodeCoverage directory upon install.  Is it present ? You could delete this directory and try again.  Do you have multiple installs of visual studio ?

**Comment by Abhijith-Pradeep** [comment]
yes, the folder was present, i deleted it and tried running the tests, i even tried reinstalling FCC extension in VS, but the problem still persists :(
And currently there is only one version of visual studio in my system.

**Comment by tonyhallett** [comment]
What is the contents of the FineCodeCoverage directory ? If you delete the directory you will need to restart vs.  before you run tests check that has installed the directory

**Comment by Abhijith-Pradeep** [comment]
its working now after deleting the folder and restarting VS, i can see the coverage details.
Thank you so much! :)
