### ISSUE TITLE
Enable/Disable Code Coverage for Integration Tests

### ISSUE THREAD

**Issue by vivekkpatel** [FortuneN/FineCodeCoverage#95]
### Installed product versions
- Visual Studio: [example 2019 Community]
- This extension: [example 1.1.116]

### Description
I have Two Test Project for My class Library One for Unit Test and One for Integration Test. Now Problem is whenever I want to run specific Integration test FCC Run Code Coverage for all tests. So, Every time I run single Integration Test Lots of Files are generated and from other integration Test.

### Steps to recreate
Here is My Project Structure
![image](https://user-images.githubusercontent.com/60865708/108063571-69059e00-7081-11eb-96f7-4bc545eb434e.png)

### Current behaviour
If I run Single Integration Test. FCC will run all integration test for code coverage which is very time consuming and generate lots of unnecessary files on my system.

### Expected behaviour
I want to Option to Enable/Disable Code Coverage for this specific Integration Test Project

### Log Files
```
Fine Code Coverage : Initializing

Fine Code Coverage : Initialized

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (Grillage.IntTests)

Fine Code Coverage : OpenCover Run (Grillage.IntTests) Arguments 
 -mergebyhash 
 -hideskipped:all 
 -register:path32 
 "-target:C:\Users\Ryzen2600x\AppData\Local\FineCodeCoverage\msTestPlatform\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" 
 "-filter:+[*]* -[xunit.*]* -[FluentAssertions]* -[Moq]* -[*]Grillage.IntTests.*" 
 "-excludebyfile:**/Migrations/*" 
 "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" 
 "-targetargs:\"C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\build-output\Grillage.IntTests.dll\" " 
 "-output:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml"

Fine Code Coverage : OpenCover Run (Grillage.IntTests)
Executing: C:\Users\Ryzen2600x\AppData\Local\FineCodeCoverage\msTestPlatform\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.7.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (32-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:01.12]   Discovering: Grillage.IntTests
[xUnit.net 00:00:01.28]   Discovered:  Grillage.IntTests
[xUnit.net 00:00:01.28]   Starting:    Grillage.IntTests
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M15a_NoMesh [1s 423ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M33a_NoMesh [1s 555ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M17a_NoMesh [775ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M02_MeshByParts [2s 642ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M34_NoMesh [1s 460ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_MeshByNumber [1s 72ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M43_MeshBySize [4s 86ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M33_MeshByNumber [3s 154ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M11_MeshByParts [4s 318ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M18a_NoMesh [1s 75ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M04_MeshByParts [4s 565ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M04_NoMesh [695ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M02a_NoMesh [450ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M11_AutoMesh [2s 725ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M01_AutoMesh [1s 640ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M42_MeshByParts [8s 769ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M01_MeshByParts [3s 19ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M11_MeshBySize [4s 309ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M21_MeshByNumber [15s 7ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M02_MeshByNumber [1s 70ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M12_NoMesh [1s 41ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M02_AutoMesh_Mirror [1s 229ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M17_NoMesh [811ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M42_AutoMesh_Mirror [3s 645ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M02_AutoMesh [1s 304ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M01_NoMesh [634ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13a_AutoMesh [2s 622ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M01_MeshBySize [3s 717ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M05a_NoMesh [447ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M42_MeshByNumber [6s 22ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M12_MeshBySize [3s 434ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M04_AutoMesh [972ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M34_MeshByNumber [17s 349ms]
[xUnit.net 00:00:26.37]       System.NullReferenceException : Object reference not set to an instance of an object.
[xUnit.net 00:00:26.37]       Stack Trace:
[xUnit.net 00:00:26.37]            at Structure.Converter.NodePoint2DConverter.Convert(Point2D point)
[xUnit.net 00:00:26.37]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs(39,0): at Grillage.Grid.TransMeshGrid.Calculate(MainGrid mainGrid)
[xUnit.net 00:00:26.37]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs(104,0): at Grillage.GrillageModel.CalculateGrids()
[xUnit.net 00:00:26.37]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs(54,0): at Grillage.GrillageModel.GenerateModelGeometry()
[xUnit.net 00:00:26.37]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs(64,0): at Grillage.GrillageModel.GenerateModel()
[xUnit.net 00:00:26.37]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\GrillageModelTest_M0.cs(167,0): at Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_MeshBySize()
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13a_MeshByNumber [2s 58ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_MeshByParts [1s 372ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M22_MeshBySize [9s 888ms]
  X Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_MeshBySize [53ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Structure.Converter.NodePoint2DConverter.Convert(Point2D point)
   at Grillage.Grid.TransMeshGrid.Calculate(MainGrid mainGrid) in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs:line 39
   at Grillage.GrillageModel.CalculateGrids() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs:line 104
   at Grillage.GrillageModel.GenerateModelGeometry() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs:line 54
   at Grillage.GrillageModel.GenerateModel() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs:line 64
   at Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_MeshBySize() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\GrillageModelTest_M0.cs:line 167
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M05_NoMesh [424ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M18_NoMesh [1s 26ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13_NoMesh [745ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M01_MeshByNumber [1s 419ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M16_NoMesh [788ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M41_MeshByNumber [5s 989ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M31_MeshByParts [5s 378ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M02_MeshBySize [2s 162ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13a_MeshByParts [2s 17ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M02_NoMesh [433ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_NoMesh [432ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M14_NoMesh [1s 73ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M31_NoMesh [1s 459ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M12_AutoMesh_Mirror [2s 704ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M16a_NoMesh [756ms]
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M04_MeshByNumber [4s 551ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M31_MeshByNumber [4s 108ms]
[xUnit.net 00:00:36.25]       System.NotImplementedException : The method or operation is not implemented.
[xUnit.net 00:00:36.25]       Stack Trace:
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Mesh\MeshGenerator0.cs(37,0): at Grillage.Mesh.MeshGenerator0.CalculateMesh_Mid_Tapered()
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Mesh\MeshGenerator0.cs(31,0): at Grillage.Mesh.MeshGenerator0.GenerateMesh()
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Mesh\AutomaticMeshGenerator.cs(25,0): at Grillage.Mesh.AutomaticMeshGenerator.CalculateQuadMeshInputs()
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs(80,0): at Grillage.Grid.TransMeshGrid.ModifyQuadMeshInput(MainGrid mainGrid)
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs(55,0): at Grillage.Grid.TransMeshGrid.CalculateQuadMeshInputs(MainGrid mainGrid)
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs(26,0): at Grillage.Grid.TransMeshGrid.Calculate(MainGrid mainGrid)
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs(104,0): at Grillage.GrillageModel.CalculateGrids()
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs(54,0): at Grillage.GrillageModel.GenerateModelGeometry()
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs(64,0): at Grillage.GrillageModel.GenerateModel()
[xUnit.net 00:00:36.25]         C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\GrillageModelTest_M0.cs(187,0): at Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_AutoMesh()
  û Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M08_NoMesh [433ms]
  X Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_AutoMesh [46ms]
  Error Message:
   System.NotImplementedException : The method or operation is not implemented.
  Stack Trace:
     at Grillage.Mesh.MeshGenerator0.CalculateMesh_Mid_Tapered() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Mesh\MeshGenerator0.cs:line 37
   at Grillage.Mesh.MeshGenerator0.GenerateMesh() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Mesh\MeshGenerator0.cs:line 31
   at Grillage.Mesh.AutomaticMeshGenerator.CalculateQuadMeshInputs() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Mesh\AutomaticMeshGenerator.cs:line 25
   at Grillage.Grid.TransMeshGrid.ModifyQuadMeshInput(MainGrid mainGrid) in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs:line 80
   at Grillage.Grid.TransMeshGrid.CalculateQuadMeshInputs(MainGrid mainGrid) in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs:line 55
   at Grillage.Grid.TransMeshGrid.Calculate(MainGrid mainGrid) in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\Grid\TransMeshGrid.cs:line 26
   at Grillage.GrillageModel.CalculateGrids() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs:line 104
   at Grillage.GrillageModel.GenerateModelGeometry() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs:line 54
   at Grillage.GrillageModel.GenerateModel() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage\GrillageModel.cs:line 64
   at Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_AutoMesh() in C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\GrillageModelTest_M0.cs:line 187
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13_MeshBySize [1s 380ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M15b_NoMesh [332ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13_MeshByNumber [1s 140ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M32_AutoMesh [2s 829ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13a_MeshBySize [1s 313ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M12_AutoMesh [1s 766ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M12_MeshByNumber [2s 763ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13a_NoMesh [528ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M44_MeshByParts [16s 2ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M11_MeshByNumber [2s 732ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M42_AutoMesh [2s 415ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M14_AutoMesh [1s 858ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M24_MeshByNumber [23s 263ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M34_MeshByParts [11s 578ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M41_AutoMesh [3s 937ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M34_AutoMesh [2s 672ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M44_NoMesh [1s 275ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M34a_NoMesh [1s 21ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M22_AutoMesh [4s 519ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M24a_NoMesh [1s 364ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M32_MeshBySize [2s 640ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M21_NoMesh [1s 478ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M33_AutoMesh [1s 585ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M24_NoMesh [1s 428ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M32_NoMesh [931ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M41_MeshByParts [5s 772ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M14_MeshByParts [12s 288ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13_AutoMesh [1s 552ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M32_MeshByParts [3s 651ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M21_MeshBySize [4s 548ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M32_MeshByNumber [2s 602ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M31_AutoMesh [2s 596ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M33_NoMesh [723ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M31_MeshBySize [2s 624ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M44_MeshByNumber [13s 648ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M32_AutoMesh_Mirror [2s 611ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M41_NoMesh [1s 243ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M14_MeshByNumber [12s 295ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M33_MeshBySize [2s 41ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M13_MeshByParts [1s 325ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M43_MeshByParts [2s 985ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M12_MeshByParts [1s 762ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M11_NoMesh [690ms]
  û Grillage.IntTests.GrillageModelTest_M3.GenerateModel_M33_MeshByParts [3s 7ms]
  û Grillage.IntTests.GrillageModelTest_M1.GenerateModel_M15_NoMesh [350ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M43_AutoMesh [1s 996ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M45_NoMesh [373ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M24_MeshByParts [16s 923ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M23_NoMesh [250ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M23_AutoMesh [767ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M44_AutoMesh [1s 564ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M23_MeshByNumber [825ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M22_NoMesh [349ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M42_MeshBySize [1s 302ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M23_MeshBySize [666ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M41_MeshBySize [1s 289ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M22_MeshByNumber [1s 76ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M24_AutoMesh [1s 90ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M43_MeshByNumber [1s 157ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M43_NoMesh [373ms]
  û Grillage.IntTests.GrillageModelTest_M4.GenerateModel_M42_NoMesh [503ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M22_MeshByParts [1s 26ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M21_AutoMesh [461ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M21_MeshByParts [1s 23ms]
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M22_AutoMesh_Mirror [590ms]
[xUnit.net 00:01:28.40]   Finished:    Grillage.IntTests
  û Grillage.IntTests.GrillageModelTest_M2.GenerateModel_M23_MeshByParts [464ms]

Total tests: 122
     Passed: 120
     Failed: 2
 Total time: 1.4770 Minutes
Committing...
Visited Classes 85 of 105 (80.95)
Visited Methods 572 of 708 (80.79)
Visited Points 3879 of 4595 (84.42)
Visited Branches 777 of 1123 (69.19)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 85 of 111 (76.58)
Alternative Visited Methods 572 of 744 (76.88)

[xUnit.net 00:00:26.37]     Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_MeshBySize [FAIL]
[xUnit.net 00:00:36.25]     Grillage.IntTests.GrillageModelTest_M0.GenerateModel_M03_AutoMesh [FAIL]
Test Run Failed.

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-02-16T17:59:32: Arguments
2021-02-16T17:59:32:  -targetdir:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output
2021-02-16T17:59:32:  -reports:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml
2021-02-16T17:59:32:  -reporttypes:Cobertura
2021-02-16T17:59:32: Writing report file 'C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-02-16T17:59:32: Report generation took 0.2 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:C:\USERS\RYZEN2600X\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_72DD08FF\EXTENSIONS\PEXG3QCF.YKX\ReportGeneratorPlugins.dll"
"-reporttypes:FccDark"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-02-16T17:59:33: Arguments
2021-02-16T17:59:33:  -targetdir:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output
2021-02-16T17:59:33:  -reports:C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-02-16T17:59:33:  -plugins:C:\USERS\RYZEN2600X\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_72DD08FF\EXTENSIONS\PEXG3QCF.YKX\ReportGeneratorPlugins.dll
2021-02-16T17:59:33:  -reporttypes:FccDark
2021-02-16T17:59:33: Writing report file 'C:\Users\Ryzen2600x\source\repos\Grillage\Grillage.IntTests\bin\Debug\fine-code-coverage\coverage-tool-output\index.html'
2021-02-16T17:59:33: Report generation took 0.4 seconds

Fine Code Coverage : ================================== DONE ==================================
```

**Comment by vivekkpatel** [comment]
Used project level settings
```
<PropertyGroup Label="FineCodeCoverage">
    <Enabled>
      True
    </Enabled>
    <Exclude>
      [xunit.*]*
      [FluentAssertions]*
      [Moq]*
    </Exclude>
    <Include>
      [*]*
    </Include>
    <ExcludeByFile>
      **/Migrations/*
      **/Hacks/*.cs
    </ExcludeByFile>
    <ExcludeByAttribute>
      MyCustomExcludeFromCodeCoverage
    </ExcludeByAttribute>
    <IncludeTestAssembly>
      True
    </IncludeTestAssembly>
  </PropertyGroup>
```
